### ISSUE TITLE
Attestation error messages are poorly constructed

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#2031] opened 2022-05-23 17:50 UTC
During release testing, we continue to run into attestation failures that are very difficult to understand, and result in the client just logging their verifier, which contains a massive byte array:

> oof its a byte array
>
```
2022-05-20 21:49:59.760760460 UTC DEBG Verifier: Verifier { trust_anchors: [[48, 130, 5, 75, 48, 130, 3, 179, 160, 3, 2, 1, 2, 2, 9, 0, 209, 7, 118, 93, 50, 163, 176, 148, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 126, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 11, 48, 9, 6, 3, 85, 4, 8, 12, 2, 67, 65, 49, 20, 48, 18, 6, 3, 85, 4, 7, 12, 11, 83, 97, 110, 116, 97, 32, 67, 108, 97, 114, 97, 49, 26, 48, 24, 6, 3, 85, 4, 10, 12, 17, 73, 110, 116, 101, 108, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 49, 48, 48, 46, 6, 3, 85, 4, 3, 12, 39, 73, 110, 116, 101, 108, 32, 83, 71, 88, 32, 65, 116, 116, 101, 115, 116, 97, 116, 105, 111, 110, 32, 82, 101, 112, 111, 114, 116, 32, 83, 105, 103, 110, 105, 110, 103, 32, 67, 65, 48, 32, 23, 13, 49, 54, 49, 49, 49, 52, 49, 53, 51, 55, 51, 49, 90, 24, 15, 50, 48, 52, 57, 49, 50, 51, 49, 50, 51, 53, 57, 53, 57, 90, 48, 126, 49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 11, 48, 9, 6, 3, 85, 4, 8, 12, 2, 67, 65, 49, 20, 48, 18, 6, 3, 85, 4, 7, 12, 11, 83, 97, 110, 116, 97, 32, 67, 108, 97, 114, 97, 49, 26, 48, 24, 6, 3, 85, 4, 10, 12, 17, 73, 110, 116, 101, 108, 32, 67, 111, 114, 112, 111, 114, 97, 116, 105, 111, 110, 49, 48, 48, 46, 6, 3, 85, 4, 3, 12, 39, 73, 110, 116, 101, 108, 32, 83, 71, 88, 32, 65, 116, 116, 101, 115, 116, 97, 116, 105, 111, 110, 32, 82, 101, 112, 111, 114, 116, 32, 83, 105, 103, 110, 105, 110, 103, 32, 67, 65, 48, 130, 1, 162, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0, 3, 130, 1, 143, 0, 48, 130, 1, 138, 2, 130, 1, 129, 0, 159, 60, 100, 126, 181, 119, 60, 187, 81, 45, 39, 50, 192, 215, 65, 94, 187, 85, 160, 250, 158, 222, 46, 100, 145, 153, 230, 130, 29, 185, 16, 213, 49, 119, 55, 9, 119, 70, 106, 106, 94, 71, 134, 204, 210, 221, 235, 212, 20, 157, 106, 47, 99, 37, 82, 157, 209, 12, 201, 135, 55, 176, 119, 156, 26, 7, 226, 156, 71, 161, 174, 0, 73, 72, 71, 108, 72, 159, 69, 165, 161, 93, 122, 200, 236, 198, 172, 198, 69, 173, 180, 61, 135, 103, 157, 245, 156, 9, 59, 197, 162, 233, 105, 108, 84, 120, 84, 27, 151, 158, 117, 75, 87, 57, 20, 190, 85, 211, 47, 244, 192, 157, 223, 39, 33, 153, 52, 205, 153, 5, 39, 179, 249, 46, 215, 143, 191, 41, 36, 106, 190, 203, 113, 36, 14, 243, 156, 45, 113, 7, 180, 71, 84, 90, 127, 251, 16, 235, 6, 10, 104, 169, 133, 128, 33, 158, 54, 145, 9, 82, 104, 56, 146, 214, 165, 226, 168, 8, 3, 25, 62, 64, 117, 49, 64, 78, 54, 179, 21, 98, 55, 153, 170, 130, 80, 116, 64, 151, 84, 162, 223, 232, 245, 175, 213, 254, 99, 30, 31, 194, 175, 56, 8, 144, 111, 40, 167, 144, 217, 221, 159, 224, 96, 147, 155, 18, 87, 144, 197, 128, 93, 3, 125, 245, 106, 153, 83, 27, 150, 222, 105, 222, 51, 237, 34, 108, 193, 32, 125, 16, 66, 181, 201, 171, 127, 64, 79, 199, 17, 192, 254, 71, 105, 251, 149, 120, 177, 220, 14, 196, 105, 234, 26, 37, 224, 255, 153, 20, 136, 110, 242, 105, 155, 35, 91, 180, 132, 125, 214, 255, 64, 182, 6, 230, 23, 7, 147, 194, 251, 152, 179, 20, 88, 127, 156, 253, 37, 115, 98, 223, 234, 177, 11, 59, 210, 217, 118, 115, 161, 164, 189, 68, 196, 83, 170, 244, 127, 193, 242, 211, 208, 243, 132, 247, 74, 6, 248, 156, 8, 159, 13, 166, 205, 183, 252, 238, 232, 201, 130, 26, 142, 84, 242, 92, 4, 22, 209, 140, 70, 131, 154, 95, 128, 18, 251, 221, 61, 199, 77, 37, 98, 121, 173, 194, 192, 213, 90, 255, 111, 6, 34, 66, 93, 27, 2, 3, 1, 0, 1, 163, 129, 201, 48, 129, 198, 48, 96, 6, 3, 85, 29, 31, 4, 89, 48, 87, 48, 85, 160, 83, 160, 81, 134, 79, 104, 116, 116, 112, 58, 47, 47, 116, 114, 117, 115, 116, 101, 100, 115, 101, 114, 118, 105, 99, 101, 115, 46, 105, 110, 116, 101, 108, 46, 99, 111, 109, 47, 99, 111, 110, 116, 101, 110, 116, 47, 67, 82, 76, 47, 83, 71, 88, 47, 65, 116, 116, 101, 115, 116, 97, 116, 105, 111, 110, 82, 101, 112, 111, 114, 116, 83, 105, 103, 110, 105, 110, 103, 67, 65, 46, 99, 114, 108, 48, 29, 6, 3, 85, 29, 14, 4, 22, 4, 20, 120, 67, 123, 118, 166, 126, 188, 208, 175, 126, 66, 55, 235, 53, 124, 59, 135, 1, 81, 60, 48, 31, 6, 3, 85, 29, 35, 4, 24, 48, 22, 128, 20, 120, 67, 123, 118, 166, 126, 188, 208, 175, 126, 66, 55, 235, 53, 124, 59, 135, 1, 81, 60, 48, 14, 6, 3, 85, 29, 15, 1, 1, 255, 4, 4, 3, 2, 1, 6, 48, 18, 6, 3, 85, 29, 19, 1, 1, 255, 4, 8, 48, 6, 1, 1, 255, 2, 1, 0, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 3, 130, 1, 129, 0, 120, 95, 45, 96, 197, 200, 10, 244, 42, 121, 118, 16, 33, 57, 21, 218, 130, 201, 178, 158, 137, 224, 144, 42, 37, 166, 199, 91, 22, 9, 28, 104, 171, 32, 74, 174, 113, 24, 137, 73, 44, 126, 30, 50, 9, 17, 69, 90, 143, 193, 52, 66, 49, 46, 119, 166, 57, 148, 217, 151, 149, 200, 234, 69, 118, 130, 60, 234, 138, 209, 225, 145, 207, 168, 98, 250, 184, 169, 50, 211, 217, 176, 83, 90, 7, 2, 208, 85, 95, 116, 229, 32, 227, 3, 48, 243, 52, 128, 231, 173, 201, 215, 200, 30, 32, 112, 49, 66, 191, 0, 197, 40, 168, 11, 70, 51, 129, 253, 96, 42, 130, 199, 3, 82, 129, 170, 229, 149, 98, 204, 181, 51, 78, 168, 144, 62, 101, 11, 1, 6, 129, 245, 206, 142, 182, 46, 172, 156, 65, 73, 136, 36, 58, 236, 146, 242, 91, 241, 60, 223, 247, 235, 204, 41, 142, 229, 27, 186, 90, 53, 56, 182, 107, 38, 203, 196, 90, 81, 222, 0, 60, 173, 48, 101, 49, 173, 124, 245, 212, 239, 15, 136, 5, 209, 185, 19, 61, 36, 19, 90, 179, 196, 100, 26, 47, 136, 8, 52, 157, 115, 51, 41, 94, 14, 118, 238, 75, 197, 34, 114, 50, 98, 142, 250, 128, 215, 157, 146, 171, 78, 61, 17, 32, 243, 251, 90, 209, 25, 205, 141, 84, 74, 161, 212, 166, 134, 94, 107, 87, 190, 172, 87, 113, 48, 126, 46, 60, 185, 7, 13, 164, 123, 75, 252, 136, 105, 224, 20, 19, 234, 9, 53, 65, 222, 138, 121, 40, 17, 183, 70, 54, 197, 233, 20, 82, 207, 12, 238, 89, 242, 251, 64, 74, 205, 11, 197, 132, 203, 156, 131, 84, 4, 115, 76, 14, 126, 198, 96, 92, 223, 207, 47, 244, 57, 182, 212, 113, 159, 112, 47, 14, 12, 63, 160, 79, 219, 18, 166, 203, 42, 209, 171, 28, 154, 241, 248, 244, 195, 160, 142, 221, 114, 163, 43, 11, 181, 208, 173, 37, 111, 253, 21, 154, 104, 59, 42, 90, 31, 29, 17, 250, 98, 83, 47, 3, 215, 84, 202, 239, 13, 165, 115, 90, 30, 90, 136, 76, 126, 137, 217, 18, 24, 201, 215]], report_body_verifiers: [Debug(DebugVerifier { allow_debug: true })], quote_verifiers: [], ias_verifiers: [], status_verifiers: [Signer(MrSignerVerifier { mr_signer: MrSigner: [126, 229, 226, 157, 116, 98, 63, 219, 198, 251, 241, 69, 75, 230, 243, 187, 11, 134, 193, 35, 102, 183, 180, 120, 173, 19, 53, 62, 68, 222, 132, 17], product_id: 1, minimum_svn: 2, config_ids: [], sw_ids: ["INTEL-SA-00334"] })] }, mc.app: mobilecoind, mc.module: mobilecoind, mc.src: mobilecoind/src/bin/main.rs:36
```
> [3:51]did we have a converter somewhere?

When attestation fails, the client should print an intelligent error message e.g. "MRSIGNER mismatch, expected: {}, found: {}" instead of dumping a large amount of irrelevant data.

Making error messages human-friendly and actionable is part of our engineering culture, and part of Rust software culture generally. The attestation code is currently a big sore spot. This is too important to just let it continue to be substandard.

**Comment by jcape** [comment] 2022-05-23 23:35
This is a duplicate of #2035 1129

**Closed by jcape** 2022-05-23 23:35 UTC
